[project]
name = "sleeper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "environs>=14.1.0",
    "espn-api>=0.44.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ptpython>=3.0.29",
]
